// Generated by Obsidian Export — Nubien - AI Agency & Studio (copy)
// Page: /404 · 02/07/2026
import './styles.css'


export default function 404() {
  return (
    <div style={{ background: '#000000', minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
    <div style={{ background: 'rgb(0, 0, 0)', width: '1200px', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px }}>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px 80px 160px 80px', display: 'flex', flexDirection: 'column', gap: 120px }}>
        <div style={{ width: '1fr', height: '80px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 120px 0px 120px', display: 'flex', flexDirection: 'column', gap: 70px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 38px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 26px, overflow: 'hidden' }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 34px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 12px }} />
          </div>
        </div>
      </div>
      <div style={{ height: '810px', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }}>
        <div style={{ width: '1fr', height: '100px' }} />
        <div style={{ height: '70%', overflow: 'hidden' }} />
      </div>
    </div>
    <div style={{ background: 'rgb(0, 0, 0)', width: '810px', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px }}>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px 80px 120px 80px', display: 'flex', flexDirection: 'column', gap: 100px }}>
        <div style={{ width: '1fr', height: '80px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 50px 0px 50px', display: 'flex', flexDirection: 'column', gap: 70px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 38px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 26px, overflow: 'hidden' }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 34px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 12px }} />
          </div>
        </div>
      </div>
      <div style={{ height: '810px', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }}>
        <div style={{ width: '1fr', height: '100px' }} />
        <div style={{ height: '70%', overflow: 'hidden' }} />
      </div>
    </div>
    <div style={{ background: 'rgb(0, 0, 0)', width: '390px', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px }}>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px 30px 120px 30px', display: 'flex', flexDirection: 'column', gap: 80px }}>
        <div style={{ width: '1fr', height: '80px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 30px 0px 30px', display: 'flex', flexDirection: 'column', gap: 70px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 38px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 26px, overflow: 'hidden' }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 34px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 12px }} />
          </div>
        </div>
      </div>
      <div style={{ width: '110%', height: '810px', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px, overflow: 'hidden' }}>
        <div style={{ width: '1fr', height: '100px' }} />
        <div style={{ height: '70%', overflow: 'hidden' }} />
      </div>
    </div>
    </div>
  )
}
